### ISSUE TITLE
Have internal RO pkg or one by active volunteer test CRAN submittal with `rev` roles

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding-meta#1]
Since R 3.4.0, using the non-standard MARC roles in `person()` in the DESCRIPTION `Authors@R` no longer throws in error, but results in only CRAN NOTE.  This makes available the `rev` (reviewer) role, which wouold be an appropriate for package authors to acknowledge reviewers while still maintaining a separation of roles between reviewers and contributors.  This can be done like so:

`person("Lincoln", "Mullen", role = c("rev"), comment = "Lincoln Mullen reviewed the package for rOpenSci, see https://github.com/ropensci/onboarding/issues/45")`

We'd to make this common practice but want a successful test run for putting a package with this on CRAN before advertising it.  @njahn82, you have a package near the end of the review process and have expressed an interest in adding reviewers as contributors (https://github.com/ropensci/onboarding/issues/115#issuecomment-310643824).  Would you be willing to test-run this with your next CRAN update?

**Comment by noamross** [comment]
While we think doing this is good community practice,
- Reviewers should only be included if they consent to this
- It is 100% up the the package author whether they want to acknowledge reviewers in this way.

**Comment by njahn82** [comment]
Sounds great, would love to test-run this when the reviewers agree on being added!

**Comment by njahn82** [comment]
@noamross my submission to CRAN with reviewer role "rev" was not successful because "R does not know about role "rev"." 

Will acknowledge the reviewers via the contributor role with link to the onboarding process.

**Comment by noamross** [comment]
Thanks @njahn82. Can you clarify where you got this response? Was it an email from one of the maintainers (could you paste it here)? Was there anything in the automated package checks on CRAN?

**Comment by njahn82** [comment]
I forwarded you the email because I don't know if it is ok to share the response in public. It felt like they are open to fully support this role in near future. Maybe, it the issue could be pushed through the R-devel list.

Here's the response of the first automated test

```
Dear maintainer,

package roadoi_0.3.tar.gz does not pass the incoming checks automatically, please see the pre-test at:
<https://win-builder.r-project.org/incoming_pretest/170716_185122_roadoi_03/00check.log>
Status: 2 NOTEs

Current CRAN status: WARN: 1, OK: 11
See: <https://CRAN.R-project.org/web/checks/check_results_roadoi.html>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/170716_185122_roadoi_03>
The files will be removed after roughly 7 days.


Best regards,
CRAN teams' auto-check service
```

I replied to this email asking for accepting the `rev` role.

**Comment by maelle** [comment]
Update, now the role raises no NOTE and the Authors is built correctly from Authors@R *for R-devel*.

* I could successfully submit `rtimicropem`.

* @mpadge will soon submit `bikedata` (recently onboarded).

**Comment by mpadge** [comment]
I've done that. Had to build on `r-devel`, after which it only threw notes on `r-release` and `r-oldrelease`, but no notes at all on CRAN `r-devel`. I noted the notes in my submission and it all went through automatically.

**Comment by maelle** [comment]
Thanks for the experience report!

**Comment by maelle** [comment]
I think we can close this issue? I recently submitted a package with a rev role ([`opencage`](https://cran.r-project.org/web/packages/opencage/index.html)) and I had no problem.

**Comment by sckott** [comment]
+1 but @noamross opened so i'll see what he thinks

**Comment by noamross** [comment]
Yes, I'll close and move on to the long-planned blog post!
