### ISSUE TITLE
Auto-response to reviewer volunteer form

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding-meta#10]
So that people who volunteer via form understand that it can take time before something comes up, they should get an auto-reply (or possibly just an explanatory splash page after the form is submitted).

- [ ] Draft text for email/splash page (in this is sue is fine) (Maelle)
- [ ] Add splash page text to form (Karthik)
- [ ] Add a column of `date_volunteered` to the Airtable and have the Zapier integration fill it out. (Karthik)

**Comment by maelle** [comment]
If splash page what about

"Thanks for volunteering as a reviewer!

We value your enthusiasm a lot. However, it might take a while before a submission corresponding to your profile comes up, so don't worry if you don't get asked to review in the very near future.

Thanks again, and see you soon in the onboarding repo!"

**Comment by noamross** [comment]
Maybe also add this to the explanatory text of question 6 on the form:

"Your answers to this and the following questions will help editors determine which packages would be a good match for you to review."

**Comment by karthik** [comment]
All completed! 🎉

**Comment by maelle** [comment]
So cool! I feel like volunteering to see it in action!
