### ISSUE TITLE
CONTRIBUTING.md guidelines or template

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding-meta#13]
As a supplement for the packaging guide.

JOSS currently requires community/contributing guidelines but isn't that specific about it:

>Community guidelines
>There should be clear guidelines for third-parties wishing to:
>
>-   Contribute to the software
>-   Report issues or problems with the software
>-   Seek support

What should be included?  @jennybc suggests

> "how we do things around here" re: roxygen, testthat, pkgdown, etc.

I generally make sure author have instructions for running local test if they are not trivial.  What else?

**Comment by noamross** [comment]
I would suggest that we provide something that is a very simple/general boiler plate that people can just use, with a blank spot for things like custom testing and then a couple of links to more elaborate ones.

**Comment by maelle** [comment]
It'd be even cooler to have this simple template added to `devtools`. `devtools::use_contributing()` or something like that.

**Comment by jennybc** [comment]
There is, in fact, an open issue about this on usethis, which is where such functions will originate in when the devtools diaspora is complete: https://github.com/r-lib/usethis/issues/12

**Comment by sckott** [comment]
would anyone be against suggesting all onboarded pkgs copy all these files  https://github.com/ropensci/dotgithubfiles into their pkgs? it's esp. useful to make sure users include session info, and esp good when it's collapsed

**Comment by noamross** [comment]
Seems useful.  For the issue template, we might suggest using reprex, as well?

**Comment by sckott** [comment]
sure - i guess not to lengthen the tangent, https://github.com/ropensci/dotgithubfiles/issues/2

**Comment by maelle** [comment]
The `usethis` function to use as model for our own function (if we decide to have our own) is `usethis::use_tidy_contributing()`

**Comment by jennybc** [comment]
I think we might pare our template down a bit FYI.

**Comment by maelle** [comment]
* Templates up at https://github.com/ropensci/dotgithubfiles/

* Helper function in `rodev`

* README of dotgithubfiles repo mentioned in dev_guide (`rodev` mentioned in that README but not directly in dev_guide yet).

* The CONTRIBUTING.md refers to a chapter for new collaborators cf https://github.com/ropensci/dev_guide/issues/46 

Further discussion please in dotgithubfiles repo or dev_guide repo. Thanks!
