### ISSUE TITLE
ropensci review blog post

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding-meta#19]
As shared in our review call a week or so ago, here's where I'm drafting the blog post: 

https://hackmd.io/EwUwLAJgzAhgDAMwLRgKwHYCMKAcokwBsYhSIcWCUAnHDNSDkA==?both

I have an actual draft now 

I think we're trying to get out next week

@ropensci/editors

**Comment by stefaniebutland** [comment]
Goal is for this post to go live Tues Sept 5.
Thanks for leading this Scott!

**Comment by maelle** [comment]
Thanks @sckott, it looks good! I added a few comments.

**Comment by sckott** [comment]
thanks @maelle
