### ISSUE TITLE
package naming: suggest names that will be easy for us to track

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding-meta#25]
we currently have for pkg naming

> We strongly recommend short, descriptive names in lower case. If your package deals with one or more commercial services, please make sure the name does not violate branding guidelines. You can check if your package name is available, informative and not offensive by using the available package.

I suggest we add some text to that paragraph about picking package names (just google it, and the less hits you get the better) so that we can track uses of them. We can spend __A LOT__ of time sifting through false positives if a package name is very generic. 

thoughts?

**Comment by maelle** [comment]
So for `monkeylearn` you would have preferred `rmonkeylearn`?

And would you want `available` to help with that?

**Comment by sckott** [comment]
hmm, i don't know. I don't think we should force people to change pkg names, but just suggest it as a tool to help us and them track its use. I imagine it's a very case by case basis kind of thing. e.g., monkeylearn is already pretty unique word, so there won't be a ton of false hits from non-monkeylearn the company things or monkeylearn the R package things. 

seems like `available`  could ping search engines to list number of hits - though don't know if thats possible with google and google scholar?

**Comment by maelle** [comment]
Another argument that I find more compelling is easiness of googling for users when they have questions

**Comment by sckott** [comment]
true, good point

**Comment by maelle** [comment]
Now no of hits only make sense compared to some sort of reference, what would that be?

**Comment by maelle** [comment]
`available` itself is bad in that regard 😂

**Comment by sckott** [comment]
when i pick a pkg name, i google many variations and pick the one with the least hits that still sorta makes sense :)

**Comment by maelle** [comment]
☺ could these variations be generated automatically?

**Comment by maelle** [comment]
In any case I agree with suggesting this strategy bc of tracking and googling.

The rest of my quesrions maybe belong to `available` issue tracker 🤔

**Comment by cboettig** [comment]
hehe, and it missed the chance for the pun: 

> what names `Ravailable` for your package?

 OTOH, the correct GitHub repo is the second hit for me on `available R`, which is pretty good (though Google searches are user-dependent these days...)  

I think asking users to use `available` to check is good; names should at least be unique on CRAN and Bioconductor and preferably not have any unintended terrible slang.  But I get the sense software developers don't see names as unique identifiers any more.  


For certain tasks, you can argue that *not* being unique is a good thing: for instance, calling your package `geojson` may mean you cannot google the package name as easily and get the package back at the top hit, but it also means that someone googling `geojson` is *more likely* to get a hit for the R package.  For things that are common formats etc, serving the latter use case of discovery is probably way more important.  Once you know the package name it's not as hard to find out where to get package-specific help.  we wouldn't want to dissuade these names when they make sense.

**Comment by maelle** [comment]
Discoverability is a very good point 👌

**Comment by maelle** [comment]
How does Google use codemeta btw?

**Comment by cboettig** [comment]
https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by maelle** [comment]
Thanks! I was wondering how a good codemeta could counterbalance a less strategic name.

**Comment by cboettig** [comment]
at the moment it won't do anything since it's not embedded into an html file.  If we embedded into, say, html version of the README page CRAN generates, or into a pkgdown site, then it would be crawled by Google.  There's currently no rich card format for software, but could still increase search rank.  

Google aside, the hope is also that this improves search in specific repositories like Datacite: https://search.datacite.org/works?query=Software

**Comment by maelle** [comment]
I'll summarize these points in a section/paragraph of the dev guide. 

I'll also add a link to @njtierney's blog post http://www.njtierney.com/post/2018/06/20/naming-things/
