### ISSUE TITLE
Add guidance about collaboration to the guide

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding-meta#31]
Thanks to a question by @dpprdan

E.g. should one review PRs / let collaborators push to a devel branch.

It's also related to personal preferences of the maintainer and the structure of the team I guess but it'd be good to add some points about it.

**Comment by sckott** [comment]
good idea. 

i'd like to include here a note about bus factor, and a nudge to maintainers that if they are generous with adding collaborators with push access they can get better software, more help, and the software is more likely to live on - but yes, i think we have to leave it up to the maintainer

**Comment by maelle** [comment]
There's a chapter in progress. https://ropensci.github.io/dev_guide/collaboration.html (not a very good structure yet)

Discussion welcome in https://github.com/ropenscilabs/dev_guide
