### ISSUE TITLE
Add guidance about GitHub access rights and security

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding-meta#34]
Disclaimer: I only set up two-factor authentication today 😱 thanks to @stephlocke 

I wonder if the bookdown about packaging best practices should include something about GitHub security. Regarding this and R security in general the guide could link to https://ropenscilabs.github.io/r-security-practices/ (that could be worked on at the same time)

Our bookdown should also highlight the rights of people within the ropensci GitHub organization (e.g. we give authors admin rights to their repo, how can they add new collaborators, are they allowed to create new repos, etc.)

**Comment by maelle** [comment]
Yes to linking out to GitHub support docs as much as possible except for

* R specific stuff, well potentially covered by https://ropenscilabs.github.io/r-security-practices/ so it'd be linking out.

* rOpenSci specific stuff which is not really security "Our bookdown should also highlight the rights of people within the ropensci GitHub organization (e.g. we give authors admin rights to their repo, how can they add new collaborators, are they allowed to create new repos, etc.)" (in editor and author guides parts of the bookdown, this is rOpenSci specific GitHub workflow and decisions)

General docs would then answer your good devil's advocate question too I suppose.

**Comment by karthik** [comment]
> Also to play devil's advocate here, what does this protect us against?

More specifically, I was thinking of limiting damage from an opsec perspective. It would be dangerous for any of rOpenSci staff (including you) to not have 2FA. 
But for individual package authors that manage public repos, what is the worst that could happen that cannot be undone? They cannot touch any other project in our org, or add new teams. Perhaps this is a discussion best had on a private forum.

**Comment by maelle** [comment]
Ah ok!

> Perhaps this is a discussion best had on a private forum.

As you wish!

**Comment by maelle** [comment]
There's a skeleton of a package about security now https://ropensci.github.io/dev_guide/package-development-security-best-practices.html

Further discussion in https://github.com/ropensci/dev_guide please. 😸
