### ISSUE TITLE
NUMFOCUS Blog post on onboarding

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding-meta#4]
Feedback from Gina re: NumFOCUS post:

After reading the original post, I'd hope for special focus/further development on the following:

- Framing: What is the specific value of a code review? (For those who are unfamiliar with this as best practice, what makes it a best practice? What "output" or "deliverable" does code review provide?) 

- More framing: If code review is uncommon in scientific computing, how is code review incorporated into open source development practices? 

- What is the process like in terms of receiving feedback, making updates, then receiving more/new feedback on the updates?

- Are there particular things that reviewers are looking for when reviewing? A matrix of best practices, for example?

- How are reviewers selected? Who are the reviewers? (How does one feel confident of the validity of the reviewers' feedback?)

- What are the top best practices that tend to be highlighted or emphasized when going through the review process?

- Takeaways for the NumFOCUS community: How would rOpenSci suggest implementing a similar code review process for other projects or communities? How can people volunteer to join the rOpenSci code review process?

length = similar to the "year in review" post

**Comment by sckott** [comment]
sorry if i'm forgetting context, but is this for a draft post we're doing  on the numfocus blog, if so, where is the draft?

**Comment by noamross** [comment]
No draft so far!  The feedback was from us sending the previous "year in reviews" post and asking her what else she was interested in.

**Comment by sckott** [comment]
ah okay.

**Comment by stefaniebutland** [comment]
Previous "year in reviews" post: https://ropensci.org/blog/blog/2016/03/28/software-review as basis for NumFOCUS post

**Comment by noamross** [comment]
Drafting location - mostly disjointed brain-dump paragraphs right now: https://hackmd.io/AwQwRgJgLAxgjCAtAVjgDgKaKgNggdkQE4AzcbHEIjAJhKJprAyA?both

**Comment by stefaniebutland** [comment]
Published post Aug 11, 2017: [How rOpenSci uses Code Review to Promote Reproducible Science](https://www.numfocus.org/blog/how-ropensci-uses-code-review-to-promote-reproducible-science/)

**Comment by sckott** [comment]
i assume we can close this now?

**Comment by noamross** [comment]
Yup
