### ISSUE TITLE
Badge API not updating

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding-meta#5]
Putting this here and tagging @karthik (on vacay, I know), as I'm not sure where the badge API lives.  I'm testing the badge with https://github.com/MarkEdmondson1234/googleLanguageR, but it doesn't seem to be updating currently.  Or does it only switch to "under review" once reviewers are assigned?

**Comment by sckott** [comment]
I do have ssh access, but looks like I need pwd that I don't have for sudo access to crontab and it's logs

**Comment by noamross** [comment]
Seems to be working now? Did someone make a change?

**Comment by karthik** [comment]
I fixed it. There was an issue with ssh keys and github timeouts. Fixed both and gave this bit its own GitHub PAT.

@sckott Tried to give you access but never got your public key. Share that with me and I'll add you.
