### ISSUE TITLE
Recommend tables for badges

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding-meta#56]
Some repos have many badges https://github.com/ropensci/ijtiff#ijtiff- that make it hard to find the information one is looking for.

Should we recommend tables like the ones in https://github.com/ropensci/drake for repos that have many badges, with a definition of "many"?

cc @cboettig

**Comment by maelle** [comment]
Another example https://github.com/ropensci/qualtRics/

**Comment by maelle** [comment]
I think that if we start recommending tables for badges with the goal of making it easier to find info at a glance, ropensci/ropenscilabs packages should use the same table structure.

@wlandau and @JasperHG90 to my knowledge your packages ([`drake`](https://github.com/ropensci/drake) and [`qualtRics`](https://github.com/ropensci/qualtRics/)) are the only ones with a badges table to date. You respectively use the structure Release | Usage | Development and Dev | Publish | Stats | Other. How did you choose the structure? Any strong opinion? 😺 

And in practice, I guess a helper function should be added to `rodev` to help organize badges (starting from a "messy" README) to make the transition easier.

**Comment by JasperHG90** [comment]
Hi @maelle . In my case, I was browsing the rOpenSci repository and came across @wlandau's drake repo. I thought his organization of the badges in a table was a neat idea so I copied that.

With respect to the table headers: it just seemed logical in my case to group them this way. 
- dev for people who are interested in this
- publish for quick overview of papers, DOI, cran link etc.
- stats tbh these are for me (make me feel good :-)) 
- other category for badges that don't fit in any of the preceding categories.

But, to be honest, I never gave these headers a lot of thought. This just seemed sensible at the time. I'm not sure if there are others who have other types of categories. Maybe do a quick survey among the rOpenSci package devs?

**Comment by maelle** [comment]
This is my quick survey of all package developers using such badges :wink: But yes I might ask in the Slack

**Comment by maelle** [comment]
And thanks for answering! ✨ 🙏

**Comment by wlandau** [comment]
I got the idea from @HenrikBengtsson: https://github.com/HenrikBengtsson/future#software-status. I do like putting badges in grids, but mobile devices do not always render them properly (ref: https://github.com/ropensci/drake/issues/203).

**Comment by rorynolan** [comment]
I like the layout in the future package too. I think the table layout is the way to go and that the table should be wider than it is long. One does not want this badge table extending too far down the README because it has limited importance relative to the other content.

**Comment by maelle** [comment]
There's no automatic tool for building a table off the badges right? Currently one would need to create it by hand?

**Comment by maelle** [comment]
Thanks all for chiming in. I added the suggestion to use a table if there are many badges to https://ropensci.github.io/dev_guide/building.html#readme, with links to three examples, without creating a standard for rOpenSci (most packages have too few badges at the moment).
