### ISSUE TITLE
CI on all platforms?

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding-meta#57]
This is a suggestion of @privefl's.

We currently advise CI on Windows in some cases https://ropensci.github.io/dev_guide/ci.html#whichci 

We do not advise to test on Mac OSX via Travis.

The downside of having CI on all platforms is that the hassle is maybe not worth it, compared to CI only on Travis + some checks on R-hub/Win-Builder before CRAN submissions + using @sckott's API to monitor CRAN check results.

Thoughts?

**Comment by sckott** [comment]
Maybe we only suggest mac builds when there is compiled code involved? do you agree @jeroen ?

**Comment by jeroen** [comment]
Yes exactly. If there is compiled code, in particular if it uses external libraries, it is important to test on different operating systems. If there is only R code or trivial C/C++ code which does not do anything platform specific, then it adds little value over the standard Linux build.

**Comment by maelle** [comment]
So criteria in https://github.com/hrbrmstr/exiv sufficient at the moment but I need to add sthg about Mac

**Comment by maelle** [comment]
Ah, now I understand your point better. I might add that the authors/reviewers can ask for help if they have any doubt. 🤔

**Comment by maelle** [comment]
Since I'm a bit wary of adding more guidelines, but agree that it doesn't hurt too much testing on several platforms, I'll add that in case of doubt, better to have too much CI than too little.

**Comment by maelle** [comment]
We might re-consider this in the future of course.
