### ISSUE TITLE
Updating the template

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding-meta#68]
Our template is quite out of date and can be immediately updated without waiting for any complex forms + integrations. Right now the critical bits of information are buried below. At the top we could have:

```
URL of software repo
Name of submitter
version 
editor
etc
```

![image](https://user-images.githubusercontent.com/138494/49035963-33f09680-f16b-11e8-9d4d-b514d6a92e94.png)

And compare with JOSS for example where all the key bits are at the top:

![image](https://user-images.githubusercontent.com/138494/49035936-21765d00-f16b-11e8-80f4-1e0c6f69b850.png)

Also see #52

**Comment by karthik** [comment]
Thanks @cboettig. This is very helpful. 

Can you take a look at this version and see if it is better: https://github.com/ropensci/onboarding/blob/template-fix/issue_template.md

cc @sckott @noamross @maelle

**Comment by karthik** [comment]
Also here is the PR for this: https://github.com/ropensci/onboarding/pull/268

**Comment by cboettig** [comment]
New template looks great!   The check-boxes for scope question are a huge help. ✨ 


 Just a few further thoughts.

- [ ] Template still links to https://github.com/ropensci/onboarding/blob/master/policies.md#overlap, which no longer resolves to anything useful.  It would be great if this could link directly to the relevant section of the dev guide.  

- [ ] Maybe it would be overkill, but there's a lot of opportunity to link to other sections in the lovely new dev guide directly now, particularly in the checkbox portion that describes things like "do you have continuous integration" etc.  Having a direct link to the dev guide for contributors that have no idea what these terms mean would be really slick.  

There are a few relatively routine checks we have for editors and reviewers that are not things we tell authors to do in the initial check-list -- for instance, I have 50/50 odds of forgetting to include a CONTRIBUTING.md until a reviewer points that out from the [reviewer checklist](https://ropensci.github.io/dev_guide/reviewtemplate.html#reviewtemplate).  I know `goodpractice` can be tricky for some users to get running locally, but it's another possible thing to mention to the authors ahead of time.

**Comment by karthik** [comment]
New template has been merged.  Thanks for these comments, Carl. In the next update we'll work to deep link into the dev guide.  🙏 .
