### ISSUE TITLE
Fill in back info in airtable

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding-meta#7]
I can tackle this - @noamross i assume you mean just missing cells for 

- affiliation
- github 
- twitter
- slack
- email

**Comment by noamross** [comment]
Yeah I had mostly meant this as a note for myself to catch up on this!  I
think you may have done most of it.

**Comment by sckott** [comment]
still some holes, will try to fill in soon

**Comment by sckott** [comment]
done
